# Generated by Django 5.2.7 on 2025-10-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_task_managers_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
            ],
        ),
    ]
